torque_offset:
  l_ank_pitch: 0
  l_ank_roll: 0
  l_hip_pitch: 0
  l_hip_roll: 0
  l_hip_yaw: 0
  l_knee: 0
  r_ank_pitch: 0
  r_ank_roll: 0
  r_hip_pitch: 0
  r_hip_roll: 0
  r_hip_yaw: 0
  r_knee: 0
